version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: >
      sh -c "
        yarn migration:run &&
        yarn seed:all &&
        yarn start:prod
      "

volumes:
  pgdata:
